### ISSUE TITLE
Cannot configure integration ‘brand’

### ISSUE THREAD

**Issue by TomStarren** [mbillow/ha-chargepoint#10]
When I’m adding this integration I get an error regarding ‘brand’.

![D63F98BA-31D1-4464-9B02-4633C5450EE5](https://user-images.githubusercontent.com/74932403/174490393-b037abf5-7ada-44a3-b9b0-1fa57dd87699.jpeg)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/chargepoint/__init__.py", line 149, in async_update_data
    hcrg_status: HomeChargerStatus = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/python_chargepoint/client.py", line 42, in check_login
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/python_chargepoint/client.py", line 296, in get_home_charger_status
    return HomeChargerStatus.from_json(
  File "/usr/local/lib/python3.9/site-packages/python_chargepoint/types.py", line 110, in from_json
    brand=json["brand"],
KeyError: 'brand'

Any idea?

**Comment by mbillow** [comment]
Interesting, the ChargePoint API isn’t telling us the brand of your charger. What kind of charger do you have?

**Comment by TomStarren** [comment]
@mbillow I’ve got an Alfen Single Pro-line.
![32FB22FC-A305-4FFA-A9DB-E60D549CBF37](https://user-images.githubusercontent.com/74932403/175833091-aa36cb58-28a5-4c7c-b78a-ffa849535a25.jpeg)

**Comment by mbillow** [comment]
@TomStarren Apologies for the wait, finally had a few seconds to tackle this. Make sure your component is updated to v0.3.1 and then restart. That should fix your issue. I'll note though that you'll likely run into #6 since you aren't using Freedom Units. 😜

**Comment by TomStarren** [comment]
When I update the integration and re-enable it I receive this error in the HA log:

`Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 23:33:36 (3 occurrences) 
Last logged: 23:33:38

Unable to install package python-chargepoint==1.6.1: ERROR: Could not find a version that satisfies the requirement python-chargepoint==1.6.1 (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.5.0, 1.6.0) ERROR: No matching distribution found for python-chargepoint==1.6.1`

HA is up2date

**Comment by mbillow** [comment]
Oop, forgot to actually release the module version:

```
Publishing python-chargepoint (1.6.1) to PyPI
 - Uploading python-chargepoint-1.6.1.tar.gz 100%
 - Uploading python_chargepoint-1.6.1-py3-none-any.whl 100%
```

Try it now. 🙊
