### ISSUE TITLE
Retrying setup: 'plug_in_reminder_time'

### ISSUE THREAD

**Issue by SurferSD** [mbillow/ha-chargepoint#2]
Successfully entered credentials. Issue immediately presents itself after entering in credentials in Integration page.

Never detects CPH50-NEMA14-50-L23 device.

Have removed and re-installed the HACS repo several times.

Logger: custom_components.chargepoint
Source: custom_components/chargepoint/__init__.py:149 
Integration: ChargePoint ([documentation](https://github.com/mbillow/ha-chargepoint), [issues](https://github.com/mbillow/ha-chargepoint/issues)) 
First occurred: 12:01:14 PM (41 occurrences) 
Last logged: 12:52:37 PM

Unexpected error fetching chargepoint data: 'plug_in_reminder_time'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/chargepoint/__init__.py", line 149, in async_update_data
    hcrg_status: HomeChargerStatus = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/python_chargepoint/client.py", line 41, in check_login
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/python_chargepoint/client.py", line 268, in get_home_charger_status
    return HomeChargerStatus.from_json(
  File "/usr/local/lib/python3.9/site-packages/python_chargepoint/types.py", line 115, in from_json
    reminder_time=json["plug_in_reminder_time"],
KeyError: 'plug_in_reminder_time'

HA: 2022.4.5
HA OS: 7.6
HACS: 1.24.5

**Comment by SurferSD** [comment]
I was able to resolve by enabling/disabling daily In-App charge reminder.
