### ISSUE TITLE
Error while setting up

### ISSUE THREAD

**Issue by rcmaehl** [mbillow/ha-chargepoint#46]
Was reviewing my logs. I have #44 but I also have:

```
2024-07-10 18:57:35.542 ERROR (MainThread) [homeassistant.components.select] Error while setting up chargepoint platform for select
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/chargepoint/select.py", line 116, in async_setup_entry
select_class(hass, client, coordinator, description, charger_id)
File "/config/custom_components/chargepoint/select.py", line 51, in __init__
self._attr_options = [str(v) for v in self.charger_status.possible_amperage_limits]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable
```

**Comment by starsoccer** [comment]
Have the same issue after adding the integration

**Comment by mbillow** [comment]
This was caused by the API occasionally returning a bare integer for `possibleChargeLimit` instead of a list, which the old code passed through directly. The rewrite in v1.0.0 uses a Pydantic model to parse the response, so this is handled correctly regardless of what the API returns. Please upgrade to v1.0.0 and let us know if you continue to see this.
